version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application container
     - run: docker build -t blockloop/rbu:$CIRCLE_BRANCH .

     # deploy the container
     - run: docker push blockloop/rbu:$CIRCLE_BRANCH
